version: "3"

services: 
  theater_seating:
    env_file: ./.env
    environment: 
      - MONGO_HOST=mongo
    build: ./
    ports:
      - "${PORT}:${PORT}"
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:${MONGO_PORT}"
    volumes:
      - mongodb_data:/data/db

volumes: 
  mongodb_data: